BASE = 'http://stat.ripe.net/data'
COUNTRY_ASN_LIST = lambda country, date : f'{BASE}/country-resource-list/data.json?resource={country}&time={date}'
BGP_UPDATE_ACTIVITY = lambda asn, starttime, endtime : f'{BASE}/bgp-update-activity/data.json?resource={asn}&starttime={starttime}&endtime={endtime}'
BGP_UPDATES = lambda asn, starttime, endtime : f'{BASE}/bgp-updates/data.json?resource={asn}&starttime={starttime}&endtime={endtime}'
BGP_STATUS = lambda asn, timestamp : f'{BASE}/bgp-state/data.json?resource={asn}&timestamp={timestamp}'
ASN_ANNOUNCED_PREFIXES = lambda asn, starttime, endtime : f'{BASE}/announced-prefixes/data.json?resource={asn}&starttime={starttime}&endtime={endtime}'
ASN_NAME_REGISTRY = lambda asn : f'{BASE}/as-overview/data.json?resource={asn}'
